locadora/config/routes.rb
Rails.application.routes.draw do
  resources :carros
  resources :emprestimos
  resources :locatarios
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"
  get "home/sobre"
end

locadora/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

locadora/app/models/carro.rb
class Carro < ApplicationRecord
    has_many :emprestimos
end

locadora/app/models/emprestimo.rb
class Emprestimo < ApplicationRecord
    belongs_to :locatario
    belongs_to :carro
    validates_associated :locatario, :carro
end

locadora/app/models/locatario.rb
class Locatario < ApplicationRecord
    has_many :emprestimos
    validate :maior_de_idade?

    def maior_de_idade?
        if data_nascimento.present? && data_nascimento > 18.years.ago.to_date
          errors.add(:data_nascimento, 'O responsável deve ser maior de idade.')
        end
    end
end

locadora/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

locadora/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

locadora/app/controllers/carros_controller.rb
class CarrosController < ApplicationController
  before_action :set_carro, only: %i[ show edit update destroy ]

  # GET /carros or /carros.json
  def index
    @carros = Carro.all
  end

  # GET /carros/1 or /carros/1.json
  def show
  end

  # GET /carros/new
  def new
    @carro = Carro.new
  end

  # GET /carros/1/edit
  def edit
  end

  # POST /carros or /carros.json
  def create
    @carro = Carro.new(carro_params)

    respond_to do |format|
      if @carro.save
        format.html { redirect_to @carro, notice: "Carro was successfully created." }
        format.json { render :show, status: :created, location: @carro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carros/1 or /carros/1.json
  def update
    respond_to do |format|
      if @carro.update(carro_params)
        format.html { redirect_to @carro, notice: "Carro was successfully updated." }
        format.json { render :show, status: :ok, location: @carro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carros/1 or /carros/1.json
  def destroy
    @carro.destroy
    respond_to do |format|
      format.html { redirect_to carros_url, notice: "Carro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carro
      @carro = Carro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def carro_params
      params.require(:carro).permit(:marca, :modelo, :cor, :revisoes_em_dia, :diaria)
    end
end

locadora/app/controllers/emprestimos_controller.rb
class EmprestimosController < ApplicationController
  before_action :set_emprestimo, only: %i[ show edit update destroy ]

  # GET /emprestimos or /emprestimos.json
  def index
    @emprestimos = Emprestimo.all
  end

  # GET /emprestimos/1 or /emprestimos/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        pdf = EmprestimoPdf.new(@emprestimo)
        send_data pdf.render, filename: "Consulta/#{@emprestimo.__id__}.pdf",
                  type: "application/pdf",
                  disposition: "inline"
      end
    end
  end

  # GET /emprestimos/new
  def new
    prepare_form
    @emprestimo = Emprestimo.new
  end

  # GET /emprestimos/1/edit
  def edit
  end

  # POST /emprestimos or /emprestimos.json
  def create
    if params[:carro]
      @emprestimo.carro = Carro.find(carro_params)
    end

    if params[:locatario]
      @emprestimo.locatario = Locatario.find(locatario_params)
    end

    @emprestimo = Emprestimo.new(emprestimo_params)

    respond_to do |format|
      if @emprestimo.save
        format.html { redirect_to @emprestimo, notice: "Emprestimo foi criado com sucesso." }
        format.json { render :show, status: :created, location: @emprestimo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @emprestimo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emprestimos/1 or /emprestimos/1.json
  def update
    respond_to do |format|
      if @emprestimo.update(emprestimo_params)
        format.html { redirect_to @emprestimo, notice: "Emprestimo foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @emprestimo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @emprestimo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emprestimos/1 or /emprestimos/1.json
  def destroy
    @emprestimo.destroy
    respond_to do |format|
      format.html { redirect_to emprestimos_url, notice: "Emprestimo foi excluido com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emprestimo
      @emprestimo = Emprestimo.find(params[:id])
    end

    def prepare_form
      @carros = Carro.order :marca
      @locatarios = Locatario.order :nome
    end
    
    # Only allow a list of trusted parameters through.
    def emprestimo_params
      params.require(:emprestimo).permit(:locatario_id, :carro_id, :data_checkin, :data_checkout, :limite_km, :meio_pagamento)
    end
end

locadora/app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!

    def index
    end

    def sobre
    end
end

locadora/app/controllers/locatarios_controller.rb
class LocatariosController < ApplicationController
  before_action :set_locatario, only: %i[ show edit update destroy ]

  # GET /locatarios or /locatarios.json
  def index
    @locatarios = Locatario.all
  end

  # GET /locatarios/1 or /locatarios/1.json
  def show
  end

  # GET /locatarios/new
  def new
    @locatario = Locatario.new
  end

  # GET /locatarios/1/edit
  def edit
  end

  # POST /locatarios or /locatarios.json
  def create
    @locatario = Locatario.new(locatario_params)

    respond_to do |format|
      if @locatario.save
        format.html { redirect_to @locatario, notice: "Locatario was successfully created." }
        format.json { render :show, status: :created, location: @locatario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @locatario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locatarios/1 or /locatarios/1.json
  def update
    respond_to do |format|
      if @locatario.update(locatario_params)
        format.html { redirect_to @locatario, notice: "Locatario was successfully updated." }
        format.json { render :show, status: :ok, location: @locatario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @locatario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locatarios/1 or /locatarios/1.json
  def destroy
    @locatario.destroy
    respond_to do |format|
      format.html { redirect_to locatarios_url, notice: "Locatario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_locatario
      @locatario = Locatario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def locatario_params
      params.require(:locatario).permit(:nome, :data_nascimento, :sexo, :endereco, :sexo)
    end
end

locadora/app/helpers/application_helper.rb
module ApplicationHelper
end

locadora/app/helpers/carros_helper.rb
module CarrosHelper
end

locadora/app/helpers/emprestimos_helper.rb
module EmprestimosHelper
end

locadora/app/helpers/home_helper.rb
module HomeHelper
end

locadora/app/helpers/locatarios_helper.rb
module LocatariosHelper
end

locadora/app/views/carros/edit.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Locadora M&Q</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        </ul>
      </div>
  </div>
</nav>
<div class="container-fluid ">
    <h2>Editar Carro</h2>

    <%= render 'form', carro: @carro %>

    <%= link_to 'Mostrar', @carro ,method: :get, class:"btn  btn-sm btn-success text-white"%>
    <%= link_to 'Voltar', carros_path,method: :get, class:"btn  btn-sm btn-success text-white"%>


</div>

locadora/app/views/carros/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <nav class="navbar navbar-expand-lg navbar-dark bg-success">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Locadora M&Q</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <li class="nav-item">
                        <%= link_to "Home", root_path, method: :get, class:"nav-link"%>
                      </li>
                  
                      <li class="nav-item">
                          <%= link_to "Locatário", locatarios_path, method: :get, class:"nav-link"%>
                      </li>

                      <li>
                          <%= link_to "Emprestimos", emprestimos_path, method: :get, class:"nav-link"%>
                      </li>

                      <li class="nav-item">
                          <%= link_to "Carros", carros_path, method: :get, class:"nav-link"%> 
                      </li>

                      <li class="nav-item">
                          <%= link_to "Sobre", "home/sobre", method: :get, class:"nav-link"%>
                      </li>

                      <li class="nav-item">
                          <%= link_to "Sair", destroy_user_session_path, method: :delete, class:"nav-link"%>  
                      </li>
            </ul>
        </div>
    </div>
  </nav>
</head>
<body>

<div class="container">
  <h2>Carro</h2>           
  <table class="table table-striped">
  
    <thead>
      <p id="notice"><%= notice %></p>
      <tr>
        <td><strong>Marca:</strong></td>
        <td><strong>Modelo:</strong></td>
        <td><strong>Cor:</strong></td>
        <td><strong>Revisões em dia:</strong></td>
        <td><strong>Diaria:</strong></td>
        <td  colspan="3"></td>
      </tr>
    </thead>
    <tbody>

      <% @carros.each do |carro| %>
        <tr>
          <td><%= carro.marca %></td>
          <td><%= carro.modelo %></td>
          <td><%= carro.cor %></td>
          <td><%= carro.revisoes_em_dia %></td>
          <td><%= carro.diaria %></td>
          <td><%= link_to 'Mostrar', carro %></td>
          <td><%= link_to 'Editar', edit_carro_path(carro) %></td>
          <td><%= link_to 'Deletar', carro, method: :delete, data: { confirm: 'Você tem Certeza?' } %></td>
        </tr>
      <% end %>
    </tbody> 
  </table>
</div>
<div class="container">
    <%= link_to 'Voltar',root_path  ,method: :get, class:"btn  btn-sm btn-success text-white"%>
    <%= link_to 'Novo Carro', new_carro_path ,method: :get, class:"btn  btn-sm btn-success text-white"%>
</div>

</body>
</html>

locadora/app/views/carros/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <nav class="navbar navbar-expand-lg navbar-dark bg-success">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Locadora M&Q</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        </ul>
      </div>
  </div>
</nav>
</head>
<body>

<div class="container">
  <h2>Carro</h2>           
  <table class="table table-striped">
  
    <thead>
      <p id="notice"><%= notice %></p>
      <tr>
        <td><strong>Marca:</strong></td>
        <td><strong>Modelo:</strong></td>
        <td><strong>Cor:</strong></td>
        <td><strong>Revisoes em dia:</strong></td>
        <td><strong>Diaria:</strong></td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @carro.marca %></td>
        <td><%= @carro.modelo %></td>
        <td><%= @carro.cor %></td>
        <td><%= @carro.revisoes_em_dia %></td>
        <td><%= @carro.diaria %></td>
  
      </tr>
      
    </tbody>
    
  </table>
</div>
<div class="container">
    <%= link_to 'Voltar',carros_path  ,method: :get, class:"btn  btn-sm btn-success text-white"%>
    <%= link_to 'Editar', edit_carro_path(@carro)  ,method: :get, class:"btn  btn-sm btn-success text-white"%>
</div>

</body>
</html>

locadora/app/views/emprestimos/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Locadora M&Q</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <%= link_to "Home", root_path, method: :get, class:"nav-link"%>
                    </li>

                    <li class="nav-item">
                        <%= link_to "Locatário", locatarios_path, method: :get, class:"nav-link"%>
                    </li>

                    <li>
                        <%= link_to "Emprestimos", emprestimos_path, method: :get, class:"nav-link"%>
                    </li>

                    <li class="nav-item">
                        <%= link_to "Carros", carros_path, method: :get, class:"nav-link"%> 
                    </li>

                    <li class="nav-item">
                        <%= link_to "Sobre", "home/sobre", method: :get, class:"nav-link"%>
                    </li>

                    <li class="nav-item">
                        <%= link_to "Sair", destroy_user_session_path, method: :delete, class:"nav-link"%>  
                    </li>
          </ul>
      </div>
  </div>
</nav>
<div class="container ">
  <h1>Empréstimos</h1>
  <table class="table table-striped">
    <p id="notice"><%= notice %></p>
      <thead>
        <tr>
          <td>Data checkin</td>
          <td>Data checkout</td>
          <td>Limite km</td>
          <td>Meio pagamento</td>
          <td colspan="3"></td>
        </tr>
      </thead>

      <tbody>
        <% @emprestimos.each do |emprestimo| %>
          <tr>
            <td><%= emprestimo.data_checkin %></td>
            <td><%= emprestimo.data_checkout %></td>
            <td><%= emprestimo.limite_km %></td>
            <td><%= emprestimo.meio_pagamento %></td>
            <td><%= link_to 'Mostrar', emprestimo %></td>
            <td><%= link_to 'Editar', edit_emprestimo_path(emprestimo) %></td>
            <td><%= link_to 'Deletar', emprestimo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

      <%= link_to 'Novo Emprestimo', new_emprestimo_path,method: :get, class:"btn  btn-sm-5 btn-success text-white"%>
      
       <%= link_to 'Voltar', root_path ,method: :get, class:"btn  btn-sm-5 btn-success text-white"%>
</div>

locadora/app/views/emprestimos/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <nav class="navbar navbar-expand-lg navbar-dark bg-success">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Locadora M&Q</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        </ul>
      </div>
  </div>
</nav>
</head>
<body>

<div class="container">
  <h2>Empréstimo</h2>           
  <table class="table table-striped">
  
    <thead>
      <p id="notice"><%= notice %></p>
      <tr>
        <td><strong>Data checkin:</strong></td>
        <td><strong>Data checkout:</strong></td>
        <td><strong>Limite km:</strong></td>
        <td><strong>Meio pagamento:</strong></td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= @emprestimo.data_checkin %></td>
        <td><%= @emprestimo.data_checkout %></td>
        <td><%= @emprestimo.limite_km %></td>
        <td><%= @emprestimo.meio_pagamento %></td>
      </tr>
      
    </tbody>
    
  </table>
</div>
<div class="container">
   <%= link_to 'Editar', edit_emprestimo_path(@emprestimo),method: :get, class:"btn  btn-sm-5 btn-success text-white"%>
  <%= link_to 'Voltar',emprestimos_path,method: :get, class:"btn  btn-sm-5 btn-success text-white"%>
</div>

</body>
</html>

locadora/app/views/home/index.html.erb
 <!DOCTYPE html>
<html>
    <head> 
        <nav class="navbar navbar-expand-lg navbar-dark bg-success">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Locadora M&Q</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <%= link_to "Home", root_path, method: :get, class:"nav-link"%>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Locatário", locatarios_path, method: :get, class:"nav-link"%>
                    </li>

                    <li>
                        <%= link_to "Emprestimos", emprestimos_path, method: :get, class:"nav-link"%>
                    </li>

                    <li class="nav-item">
                        <%= link_to "Carros", carros_path, method: :get, class:"nav-link"%> 
                    </li>

                    <li class="nav-item">
                        <%= link_to "Sobre", "home/sobre", method: :get, class:"nav-link"%>
                    </li>

                    <li class="nav-item">
                        <%= link_to "Sair", destroy_user_session_path, method: :delete, class:"nav-link"%>  
                    </li>
                </ul>
            </div>
        </div>
        </nav>
    </head>
     <body>
    
        <table>
            <tr>
                <td>
                <%= image_tag image_url('hyndai-creta-prata-frente.jpg'), class:'card-img' %>
                <div class="card-body mb-5 ">
                    <h3 class="card-subtitle mb-2 text-muted"></h3>
                </div>  
                </td>
                <td>
                     <uL class="list-group list-group-flush">
                        <h3 class="card-subtitle mb-2 text-muted">Hydai Creta 2021</h3>
                        <h1 class="card-text"> R$ 137,57</h1>
                        <li class="list-group-item">Proteção do Veículo</li>
                        <li class="list-group-item">Melhor Preço garantido</li>
                        <li class="list-group-item">KM Livre(ilimitado)</li>
                        <li class="list-group-item">Taxas da Locadora</li>
                        <li class="list-group-item">Sem Taxa de Alteração</li>
                        <li class="list-group-item">Pague no Destino</li>
                    </uL>
                        <div class="card-body">
                            <%=  link_to "Alugar", new_emprestimo_path ,method: :get, class:"btn  btn-lg btn-success text-white"%>
                        </div>
                </td> 
            </tr>    
        </table>
        
        <table>
            <tr>
                <td>
                 <%= image_tag image_url('jeep_renagete_Preto_frente.jpg'), class: 'card-img' %> 
                <div class="card-body mb-5 ">
                </div>  
                </td>
                <td>
                     <uL class="list-group list-group-flush">
                        <h3 class="card-subtitle mb-2 text-muted">Jeep Renagete</h3>
                        <h1 class="card-text"> R$ 148,80</h1>
                        <li class="list-group-item">Proteção do Veículo</li>
                        <li class="list-group-item">Melhor Preço garantido</li>
                        <li class="list-group-item">KM Livre(ilimitado)</li>
                        <li class="list-group-item">Taxas da Locadora</li>
                        <li class="list-group-item">Sem Taxa de Alteração</li>
                        <li class="list-group-item">Pague no Destino</li>
                    </uL>
                    <div class="card-body">
                         <%=  link_to "Alugar", new_emprestimo_path ,method: :get, class:"btn  btn-lg btn-success text-white"%>
                    </div>
                
                </td> 
            </tr>    
        </table>

        <table>
            <tr>
                <td>
                 <%= image_tag image_url('honda-civic-prata-frente.jpg'), class: 'card-img' %> 
                <div class="card-body mb-5 ">
                </div>  
                </td>
                <td>
                     <uL class="list-group list-group-flush">
                        <h3 class="card-subtitle mb-2 text-muted">Honda Civic</h3>
                        <h1 class="card-text"> R$ 195,50</h1>
                        <li class="list-group-item">Proteção do Veículo</li>
                        <li class="list-group-item">Melhor Preço garantido</li>
                        <li class="list-group-item">KM Livre(ilimitado)</li>
                        <li class="list-group-item">Taxas da Locadora</li>
                        <li class="list-group-item">Sem Taxa de Alteração</li>
                        <li class="list-group-item">Pague no Destino</li>
                    </uL>
                    <div class="card-body">
                         <%=  link_to "Alugar", new_emprestimo_path ,method: :get, class:"btn  btn-lg btn-success text-white"%>
                    </div>
                
                </td> 
            </tr>    
        </table>

    </body>

</html>

locadora/app/views/locatarios/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Locadora M&Q</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <%= link_to "Home", root_path, method: :get, class:"nav-link"%>
                    </li>
                    
                    <li class="nav-item">
                        <%= link_to "Locatário", locatarios_path, method: :get, class:"nav-link"%>
                    </li>

                    <li>
                        <%= link_to "Emprestimos", emprestimos_path, method: :get, class:"nav-link"%>
                    </li>

                    <li class="nav-item">
                        <%= link_to "Carros", carros_path, method: :get, class:"nav-link"%> 
                    </li>

                    <li class="nav-item">
                        <%= link_to "Sobre", "home/sobre", method: :get, class:"nav-link"%>
                    </li>

                    <li class="nav-item">
                        <%= link_to "Sair", destroy_user_session_path, method: :delete, class:"nav-link"%>  
                    </li>
          </ul>
      </div>
  </div>
</nav>
<div class="container ">
  <h1>Locatarios</h1>
  <table class="table table-striped">
  <p id="notice"><%= notice %></p>
    <thead>
      <tr>
        <th>Nome</th>
        <th>Data nascimento</th>
        <th>Sexo</th>
        <th>Endereco</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @locatarios.each do |locatario| %>
        <tr>
          <td><%= locatario.nome %></td>
          <td><%= locatario.data_nascimento %></td>
          <td><%= locatario.sexo %></td>
          <td><%= locatario.endereco %></td>
          <td><%= link_to 'Mostrar', locatario %></td>
          <td><%= link_to 'Editar', edit_locatario_path(locatario) %></td>
          <td><%= link_to 'Deletar', locatario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
    <%= link_to 'Voltar', root_path ,method: :get, class:"btn  btn-sm-5 btn-success text-white"%>
   <%= link_to 'Novo Locatario', new_locatario_path ,method: :get, class:"btn  btn-sm-5 btn-success text-white"%>
</div>

locadora/app/views/locatarios/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <nav class="navbar navbar-expand-lg navbar-dark bg-success">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Locadora M&Q</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        </ul>
      </div>
  </div>
</nav>
</head>
<body>
  <div class="container">
  <h2>Lacatário</h2>           
  <table class="table table-striped">

    <thead>
      <p id="notice"><%= notice %></p>
      <tr>
        <td><strong>Nome:</strong></td>
        <td><strong>Data nascimento:</strong></td>
        <td><strong>Sexo:</strong></td>
        <td><strong>Endereco:</strong></td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>  <%= @locatario.nome %></td>
        <td> <%= @locatario.data_nascimento %></td>
        <td><%= @locatario.sexo %></td>
        <td><%= @locatario.endereco %></td>
      </tr>   
    </tbody>   
  </table>
  </div>
    <div class="container">
      <%= link_to 'Editar',edit_locatario_path(@locatario),method: :get, class:"btn  btn-sm-5 btn-success text-white"%>
      <%= link_to 'Voltar', locatarios_path,method: :get, class:"btn  btn-sm-5 btn-success text-white"%>
    </div>
</body>
</html>